name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential \
        libssl-dev libffi-dev python3-dev libfreetype6-dev \
        libpng-dev pkg-config libgl1-mesa-dev
        pip install cython

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32stdc++6 lib32z1
        sudo apt-get install -y android-sdk
    
    - name: Set up Android SDK
      run: |
        sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "extras;google;google_play_services" "extras;android;m2repository"
        sdkmanager --install "cmdline-tools;latest" "platforms;android-30" "platforms;android-31"
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        sdkmanager --install "ndk;21.3.6528147"
        sdkmanager --install "aidl" # Installation de AIDL
        yes | sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: path/to/your/apk/file.apk

